# Generated by Django 5.2.7 on 2025-10-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la empresa')),
                ('slug', models.SlugField(unique=True)),
                ('remote', models.BooleanField(default=False, verbose_name='Remoto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Ciudad')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Persona de contacto')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Página web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
